<?php

namespace ContainerFjEfSkS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSetupMovieCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\SetupMovieCommand' shared autowired service.
     *
     * @return \App\Command\SetupMovieCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/SetupMovieCommand.php';

        $container->privates['App\\Command\\SetupMovieCommand'] = $instance = new \App\Command\SetupMovieCommand(($container->services['App\\Service\\MovieService'] ?? $container->load('getMovieServiceService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('app:setup-movie');
        $instance->setDescription('Movie create data');

        return $instance;
    }
}
