<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFjEfSkS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFjEfSkS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFjEfSkS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFjEfSkS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFjEfSkS\App_KernelDevDebugContainer([
    'container.build_hash' => 'FjEfSkS',
    'container.build_id' => '14e1061c',
    'container.build_time' => 1656626052,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFjEfSkS');
