<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_movies' => [[], ['_controller' => 'App\\Controller\\ApiController::getMovies'], [], [['text', '/v1/api/movies']], [], [], []],
    'api_movie' => [['id'], ['_controller' => 'App\\Controller\\ApiController::getMovie'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/v1/api/movies']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\ClientController::index'], [], [['text', '/']], [], [], []],
    'movies' => [[], ['_controller' => 'App\\Controller\\ClientController::movies'], [], [['text', '/film']], [], [], []],
    'movie' => [['id'], ['_controller' => 'App\\Controller\\ClientController::movie'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/film']], [], [], []],
];
